Branch1.4
Isakov11/dev-j120 pull request #6
Opened 2020-06-18 20:26 UTC by Isakov11

Добавлен интерфейс Mediator, добавлен модуль связи с БД
Прошу проверить и прокомментировать код

2020-06-18 20:27 UTC, Isakov11 commented
Добавлен интерфейс Mediator, добавлен модуль связи с БД
Прошу проверить и прокомментировать код

2020-06-21 07:31 UTC, KolosovKD requested changes
Уберите доп. библиротеки, мы пока работаем с базовым инструментарием.

2020-06-21 07:31 UTC, KolosovKD commented on createDBtablesScript.sql
> +  `article` bigint NOT NULL,
поле не является внешним ключом. Это позволит вам добавить в эту таблицу запись с таким артикулом, которого нет в таблице goods. Добавьте внешний ключ.

2020-06-21 07:31 UTC, KolosovKD commented on createDBtablesScript.sql
> +  UNIQUE KEY `key_UNIQUE` (`key`)
как правило, primary key автоматически накладывает ограничение уникальности, поэтому можно отдельно не дублировать

2020-06-21 07:31 UTC, KolosovKD commented on config.config
> +password = !Qwerty123_
Как правило, стараются подчеркнуть что настройки относятся к одной "группе". Например, так:
```
database.url = jdbc:mysql://localhost/storeDB?serverTimezone=Europe/Moscow
database.username = operator
database.password = !Qwerty123_ 
```

2020-06-21 07:31 UTC, KolosovKD commented on config.config
> +OrderPath = data\\orders.dat
Как правило, стараются не использовать кэмэлкэйс, разделяя слова точкой.
```
discount.max = 40
path.file = data\Price.csv
path.price = data\\reassesment.csv
path.order = data\\orders.dat
```

2020-06-21 07:31 UTC, KolosovKD commented on src/dao/ConnectionManager.java
> +import static com.mchange.v1.db.sql.ConnectionUtils.attemptClose;
Задание не предполагало использования дополнительных библиотек поверх JDBC

2020-06-23 14:03 UTC, Isakov11 commented
Поправил замечания

2020-08-14 14:10 UTC, merged